/** Declaration file generated by dts-gen */

export function D(): void;

export function P(target: any, ...args: any[]): any;

export function PS(target: any, input: any, ...args: any[]): any;

export function S(closure: any): any;

export function constant(a: any, b: any, ...args: any[]): any;

export function immutable(a: any, b: any, ...args: any[]): any;

export namespace D {
    const prototype: {
    };

}

export namespace P {
    const prototype: {
    };

}

export namespace PS {
    const prototype: {
    };

}

export namespace S {
    const prototype: {
    };

}

export namespace constant {
    const prototype: {
    };

}

export namespace immutable {
    const prototype: {
    };

}

